import Head from 'next/head'
import Title from '../components/Title'
import styles from '@styles/Home.module.css'
import { Page } from '../types/page'
import TermPage from '@components/TermPage'
import Mute from '@components/Mute'

const page: Page = {
  title: 'Home',
  content: {
    text: 'blah blah blah blah blah blahblah blah blahblah blah blahblah blah blahblah blah blahblah blah blahblah blah blahblah blah blah'
  },
  options: [
    {
      name: 'I am an option',
      path: 'path/to/nowhere'
    },
    {
      name: 'Projects',
      path: 'projects'
    },
    {
      name: 'Memes',
      path: 'memes'
    }
  ]
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Webterm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mute />
      <div className={styles.content}>
        <Title>Robco Industries TERMLINK PROTOCOL</Title>
        <TermPage page={page} />
      </div>
    </>
  )
}
